services:
  webapp-prod:
    image: ghcr.io/ajvarchetti/capstone_osu_webapp:main
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./webapp/config/.prod.env
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro # Mount SSL certificates
      - ./webapp/config/nginx.conf:/etc/nginx/conf.d/default.conf # Custom NGINX config

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - ./db/data:/usr/share/elasticsearch/data # Docker volume
    env_file:
      - ./db/config/.prod.env

  update-data:
    image: ghcr.io/ajvarchetti/capstone_osu_data:main
    depends_on:
      - elasticsearch
    env_file:
      - ./db/config/.prod.env
    volumes:
      - ./db:/db
    command: >
      sh -c "python3 download_topviews.py &&
            python3 download_wiki_articles.py &&
            python3 elasticsearch_import.py"

  elasticsearch-wrapper-api:
    image: ghcr.io/ajvarchetti/capstone_osu_api:main
    ports:
      - "5002:5002"
    depends_on:
      - elasticsearch
    env_file:
      - ./db/config/.prod.env
    volumes:
      - ./db:/db
    command: >
      sh -c "python3 elasticsearch_wrapper_api.py"
