services:
  webapp-dev:
    build:
      context: ./webapp
      target: dev
    ports:
      - "2825:2825"
    volumes:
      - ./webapp:/app
      - ./webapp/node_modules:/app/node_modules
    env_file:
      - ./webapp/config/.dev.env
    stdin_open: true
    tty: true

  # TODO: Configure these to run the database
  db-dev:
    build:
      context: ./db
      target: dev
    ports:
      - "2826:2826"
    volumes:
      - ./db:/app
      - ./db/node_modules:/app/node_modules
    env_file:
      - ./db/config/.dev.env
    stdin_open: true
    tty: true
